{
 "title": "Workload Logs & Cluster Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "tier", "query": "frontend, backend" }
  ]
 },
 "panels": [
  {
   "title": "Site Traffic (requests)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Site Traffic (data)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_size_sum[1m]))*-1",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_response_size_sum[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Worker Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_namespace_pod:kube_pod_info:{namespace=\"kube-system\",pod=~\"aws-node-.*\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$tier Errors (Status 4xx/5xx)",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "repeat": "tier",
   "targets": [
    {
     "expr": "{namespace=\"default\",app_kubernetes_io_instance=\"nginx-ingress-controller\"} | regexp `(?P<remote_host>\\S+) (?P<user_identifier>\\S+) (?P<user>\\S+) \\[(?P<ts>[^\\]]+)\\] \\\"(?P<method>\\S+) (?P<path>\\S+) HTTP/(?P<http_version>\\d+\\.\\d+)\\\" (?P<status>\\d+) (?P<bytes_sent>\\d+|-) \\\"(?P<host>\\S+)\\\" \\\"(?P<user_agent>.*)\\\" \\S+ \\S+ \\[(?P<k8s_service>\\S+)\\] \\[\\] (?P<endpoint_addr>\\S+) \\S+ \\S+ (?P<backend_status>\\S+) \\S+` | k8s_service =~ \".*$tier.*\" | status =~ \"4..|5..\" | line_format \"{{.ts}} {{.backend_status}}->{{.status}} {{.remote_host}}->{{.endpoint_address}} \\\"{{.method}} {{.path}} HTTP/{{.http_version}}\\\" \\\"{{.user_agent}}\\\"\""
    }
   ]
  },
  {
   "title": "$tier Errors (Status 4xx/5xx)",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{namespace=\"default\",app_kubernetes_io_instance=\"nginx-ingress-controller\"} | regexp `(?P<remote_host>\\S+) (?P<user_identifier>\\S+) (?P<user>\\S+) \\[(?P<ts>[^\\]]+)\\] \\\"(?P<method>\\S+) (?P<path>\\S+) HTTP/(?P<http_version>\\d+\\.\\d+)\\\" (?P<status>\\d+) (?P<bytes_sent>\\d+|-) \\\"(?P<host>\\S+)\\\" \\\"(?P<user_agent>.*)\\\" \\S+ \\S+ \\[(?P<k8s_service>\\S+)\\] \\[\\] (?P<endpoint_addr>\\S+) \\S+ \\S+ (?P<backend_status>\\S+) \\S+` | k8s_service =~ \".*$tier.*\" | status =~ \"4..|5..\" | line_format \"{{.ts}} {{.backend_status}}->{{.status}} {{.remote_host}}->{{.endpoint_address}} \\\"{{.method}} {{.path}} HTTP/{{.http_version}}\\\" \\\"{{.user_agent}}\\\"\""
    }
   ]
  },
  {
   "title": "database Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{pod=\"db-postgres-0\"}"
    }
   ]
  }
 ]
}